Add some internal documentation
RedstoneTools/redstonetools-mod pull request #170
Opened 2023-05-11 09:29 UTC by orbyfied

- Added developer guide "How to make a feature" to `CONTRIBUTING.md`
- Added javadocs to some classes and methods

Closes #100

2023-05-12 20:47 UTC, Matthias1590 requested changes

2023-05-12 20:47 UTC, Matthias1590 commented on CONTRIBUTING.md
> +# Developer Guide: How to make a feature
I kinda wanna refactor most of the code for features so I think its easiest if we leave the changes to CONTRIBUTING.md out and add them back after we're sure what the code is gonna look like. The other changes all seem fine to me

2023-05-12 20:48 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/arguments/Argument.java
> +    // TODO: maybe add an isSet flag and unset
Why?

2023-05-12 20:49 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/DirectionArgument.java
> +<<<<<<< HEAD
this isnt merged properly

2023-05-12 21:03 UTC, orbyfied commented on CONTRIBUTING.md
> +# Developer Guide: How to make a feature
ok

2023-05-12 21:04 UTC, orbyfied commented on src/main/java/tools/redstone/redstonetools/features/arguments/Argument.java
> +    // TODO: maybe add an isSet flag and unset
for null values

2023-05-12 21:04 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/arguments/Argument.java
> +    // TODO: maybe add an isSet flag and unset
The values shouldnt be used outside of the execute method anyway

2023-05-12 21:04 UTC, orbyfied commented on src/main/java/tools/redstone/redstonetools/utils/DirectionArgument.java
> +<<<<<<< HEAD
oh shit

2023-05-12 21:04 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/arguments/Argument.java
> +    // TODO: maybe add an isSet flag and unset
if the serializer accepts null or if the default is null then null is a valid value

2023-05-12 21:08 UTC, orbyfied commented on src/main/java/tools/redstone/redstonetools/features/arguments/Argument.java
> +    // TODO: maybe add an isSet flag and unset
yes i know but how do we know if the value is set or not when null is a valid value

2023-05-12 21:17 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/arguments/Argument.java
> +    // TODO: maybe add an isSet flag and unset
you dont need to? if the value is null its either explicitly set to null or defaulted to null, whether its set by the user or if it has that value by default shouldnt matter

2023-06-06 18:24 UTC, Matthias1590 commented
Closing this, a lot has changed since

2023-06-06 18:24 UTC, closed without merging