AirPlace Reach
RedstoneTools/redstonetools-mod pull request #210
Opened 2023-06-03 20:00 UTC by JayMensink

Issue #80 required a little refactoring, as well as a server-side removal of the reach limit.
As stated in a reply to the original issue, implementing a gamerule is not a viable solution, so the command had to be modified instead.

2023-06-03 22:34 UTC, Matthias1590 requested changes

2023-06-03 22:34 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceFeature.java
> +public class AirPlaceFeature extends CommandFeature {
airplace should be a toggleable feature, you can overload the register method to add the argument to the command

2023-06-03 22:34 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceFeature.java
> +    public void setReach(float reach) { this.reach = reach;}
getters and setters arent really needed if theyre both public and dont perform any checks

2023-06-03 22:34 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/mixin/features/AirPlaceServerMixin.java
> +        return 999;
Could be infinity instead

2023-06-03 23:13 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/mixin/features/AirPlaceServerMixin.java
> +        return 999;
Successfully changed.

2023-06-03 23:13 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceFeature.java
> +    public void setReach(float reach) { this.reach = reach;}
Successfully changed.

2023-06-03 23:13 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceFeature.java
> +public class AirPlaceFeature extends CommandFeature {
do we *really* need to override the register method? This implementation is relatively clean anyway.

2023-06-03 23:15 UTC, xtrm-en commented on src/main/java/tools/redstone/redstonetools/mixin/features/AirPlaceServerMixin.java
> +        return 999;
Check if AirPlace is enabled before returning that

2023-06-03 23:22 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/mixin/features/AirPlaceServerMixin.java
> +        return 999;
> Check if AirPlace is enabled before returning that

After much fiddling, I managed to both dynamic distance checking as well as this suggestion to work.

2023-06-04 01:07 UTC, Matthias1590 requested changes

2023-06-04 01:07 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceFeature.java
> +public class AirPlaceFeature extends CommandFeature {
This wouldnt work if we want to change the behaviour of toggleable features, if we want to show a toggle in some gui for example this wouldnt show up because itd no longer extend toggleable feature even thought it behaves like a toggleable feature

2023-06-04 10:44 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceFeature.java
> +public class AirPlaceFeature extends CommandFeature {
Successfully changed.

2023-06-04 13:03 UTC, Matthias1590 approved these changes

2023-06-04 16:07 UTC, Matthias1590 requested changes
If your reach is high and you try to place a block while looking into the air you wont be able to, mc probably sees that you have no block to place on unlike when you're looking at the ground, no matter how far it is

2023-06-04 16:07 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +        .ofType(floatArg(1.0f));
Maybe make the minimum 5, you dont really need anything less than mc's default reach

2023-06-04 16:07 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +
I think it makes sense to enable airplace if its not enabled here

2023-06-04 16:07 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +@Feature(name = "Air Place", description = "Allows you to place blocks in the air.", command = "airplace")
Please add the autoservice annotation

2023-06-04 21:02 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +@Feature(name = "Air Place", description = "Allows you to place blocks in the air.", command = "airplace")
Succesfully added.

2023-06-04 21:02 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +
Succesfully added.

2023-06-04 21:02 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +        .ofType(floatArg(1.0f));
Succesfully changed.

2023-06-04 21:07 UTC, Matthias1590 requested changes

2023-06-04 21:07 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +        AirPlaceFeature airPlaceFeature = RedstoneToolsClient.INJECTOR.getInstance(AirPlaceFeature.class);
You can keep a static reference to this

2023-06-04 21:07 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +            player.sendChatMessage("/airplace");
It's cleaner imo to just add a setter to the air place feature

2023-06-04 21:28 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +        AirPlaceFeature airPlaceFeature = RedstoneToolsClient.INJECTOR.getInstance(AirPlaceFeature.class);
Fabric crashes when I try to do this xd

2023-06-04 21:33 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/features/commands/AirPlaceReachFeature.java
> +            player.sendChatMessage("/airplace");
Successfully changed.

2023-06-05 19:46 UTC, Matthias1590 commented
Could you resolve the conflicts?

2023-06-05 22:04 UTC, JayMensink commented
This merge conflict has caused me so much trouble that I don't think I wanna do them ever again.

2023-06-06 21:29 UTC, JayMensink commented
This is so over

2023-06-06 21:29 UTC, closed without merging