Replace javax.json-api (and its implementation) with builtin Gson
RedstoneTools/redstonetools-mod pull request #214
Opened 2023-06-04 03:44 UTC by xtrm-en

### 228kb baby! :champagne: 

This commit removes the usage of a third-party dependency for Json parsing/writing and replaces its usages with Minecraft's provided [Gson](https://github.com/google/gson/) library.

This does not only refactors usages but also improves them by using Gson's binding functionality (instantiating a class automatically based on Json string values) via custom adapter classes (located in `tools.redstone.redstonetools.macros.gson`) that make it subjectively easier to write and read Json "translation" code.

2023-06-04 07:35 UTC, JukoiDev submitted a review, later dismissed
LGTM

2023-06-04 13:14 UTC, Matthias1590 requested changes

2023-06-04 13:14 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/macros/MacroManager.java
> +            throw new RuntimeException("Couldn't load macros config", t);
not being able to parse the macros shouldnt crash the game

2023-06-04 13:14 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/macros/MacroManager.java
> +        if (this.macros.isEmpty()) {
this would cause the default macros to be added the next time the game launches after the user deletes them, i think it makes more sense to only load default macros if the macro file could not be read

2023-06-04 13:14 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/macros/MacroManager.java
> +            throw new RuntimeException("Couldn't load macros config", t);
just noticed thats what it does in the older version as well, my bad, it probably shouldnt crash though

2023-06-04 13:14 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/macros/gson/ActionAdapter.java
> +            throw new RuntimeException("Unknown action type: " + action.getClass().getName());
same here, i dont think we should crash

2023-06-04 13:14 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/macros/gson/ActionAdapter.java
> +        throw new RuntimeException("Unknown action type: " + typeStr);
same here, dont think we should crash

2023-06-04 13:14 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/telemetry/TelemetryManager.java
> +            throw new RuntimeException("Coudln't load telemetry config", t);
same crashing thing here

2023-06-04 14:40 UTC, Matthias1590 requested changes

2023-06-04 14:40 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/macros/MacroManager.java
> +            throw new RuntimeException("Couldn't load macros config path", t);
I dont think we should crash

2023-06-04 14:40 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/telemetry/TelemetryManager.java
> +            throw new RuntimeException("Couldn't load telemetry config path", t);
Don't think we should crash here either

2023-06-04 14:42 UTC, xtrm-en commented on src/main/java/tools/redstone/redstonetools/macros/MacroManager.java
> +            throw new RuntimeException("Couldn't load macros config path", t);
Those crashes are redundant ones, basically where Minecraft doesn't get initialized properly, which shouldn't happen (on a release build). Additionally, if this file isn't properly found, the rest of the code would be the one to crash due to NPEs, so early throwing would be the best course of actions here.

2023-06-04 14:43 UTC, xtrm-en commented on src/main/java/tools/redstone/redstonetools/telemetry/TelemetryManager.java
> +            throw new RuntimeException("Couldn't load telemetry config path", t);
Same as previous comment

2023-06-04 14:45 UTC, Matthias1590 approved these changes

2023-06-09 17:37 UTC, Matthias1590 approved these changes

2023-06-09 17:38 UTC, Matthias1590 approved these changes

2023-06-12 17:42 UTC, Matthias1590 commented
Yeah so were gonna refactor everything and idk if it would be worth the testing to merge this, sorry

2023-06-12 17:42 UTC, closed without merging