AirPlace with Leftclick
RedstoneTools/redstonetools-mod pull request #221
Opened 2023-06-04 18:22 UTC by Dav321

resolves #132

2023-06-04 18:59 UTC, Matthias1590 requested changes
Might be nice to abstract a couple of lines into separate functions but the rest looks good

2023-06-04 18:59 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/mixin/features/AirplaceMixin.java
> +        var minecraftClient = (MinecraftClient) (Object) this;
Might be nice to abstract this into a getMinecraftClient method and then create one for getPlayer and getInteractionManager too maybe

2023-06-04 19:00 UTC, Matthias1590 commented
Also what's your discord? So I can give you the contributor role

2023-06-04 20:04 UTC, Dav321 commented
My discord is Dav32_1#5015.

2023-06-04 20:31 UTC, Matthias1590 approved these changes

2023-06-04 20:45 UTC, Dav321 commented
Changed the base branch because main is protected

2023-06-04 21:00 UTC, Matthias1590 approved these changes

2023-06-05 18:50 UTC, Matthias1590 approved these changes

2023-06-05 18:51 UTC, merged