Languages update
RedstoneTools/redstonetools-mod pull request #224
Opened 2023-06-04 20:52 UTC by ikyynites

Added translation keys for new languages, consulted friends who are fluent in these languages to check that translations were accurate and correct.

2023-06-04 21:02 UTC, xtrm-en requested changes

2023-06-04 21:02 UTC, xtrm-en commented on src/main/resources/assets/redstonetools/lang/fr_fr.json
> +    "gamerule.doContainerDrops": "Effectuer des largages de conteneurs",
This is really weirdly formulated, and doesn't follow Minecraft's official translation.

I'd suggest "Butin des conteneurs", and as a description: "Contrôle les butins des conteneurs"

2023-06-04 21:44 UTC, ikyynites commented on src/main/resources/assets/redstonetools/lang/fr_fr.json
> +    "gamerule.doContainerDrops": "Effectuer des largages de conteneurs",
it is, my friends said it was hard to translate without context, and i cant verify their translations myself. it was taking me ages to get the official translations because i couldnt find any reliable sources other than looking up the hashed names of each individual language and finding it in the minecraft assets. ill give them all another look tomorrow

2023-06-04 22:07 UTC, ikyynites commented on src/main/resources/assets/redstonetools/lang/fr_fr.json
> +    "gamerule.doContainerDrops": "Effectuer des largages de conteneurs",
ive just removed translations that i cant verify. will re-add them once i can cross-reference with the official translations for other gamerules

2023-06-05 16:21 UTC, ikyynites commented on src/main/resources/assets/redstonetools/lang/fr_fr.json
> +    "gamerule.doContainerDrops": "Effectuer des largages de conteneurs",
as of now, i would push this and add the couple languages that have been properly translated. and ill add a few more later on.

2023-06-12 17:44 UTC, closed without merging