/glass -> /colored
RedstoneTools/redstonetools-mod pull request #244
Opened 2023-06-05 22:02 UTC by maghedo243

These changes turn the GlassFeature.java into the new and improved ColoredFeature.java. The extra files are all involved with the /colored feature.

The material options:
- Glass
- Wool
- Concrete
- Terracotta
- Glazed Terracotta

2023-06-05 22:12 UTC, Matthias1590 requested changes

2023-06-05 22:12 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/ColoredFeature.java
> +    public static final Argument<ColoredBlockArgument> blockType = Argument.ofType(material());
Could you move the field declarations to the top of the file?

2023-06-05 22:12 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/ColoredBlockArgument.java
> +public enum ColoredBlockArgument {
Could probably be renamed to ColoredMaterial, it's not really related to arguments and it doesn't really represent a block either, ig ColoredBlockType could work too in which case the serializer should probably be called ColoredBlockTypeSerializer and the method that returns instance would be something like coloredBlockType()

2023-06-05 22:12 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/ColoredFeature.java
> +    private ColoredBlock getColorVariant(Block block) {
How is this different from ColoredBlock.fromBlock()?

2023-06-05 22:20 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/features/commands/ColoredFeature.java
> +    private ColoredBlock getColorVariant(Block block) {
Well I was just editing the GlassFeature code. ".fromBlock()" appears to get a blockId that is independent of the actual color that the block is. And my "getColorVariant" actually chooses the color based on the argument.

2023-06-05 22:21 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/utils/ColoredBlockArgument.java
> +public enum ColoredBlockArgument {
The only reason I named it ColoredBlockArgument was to copy the naming convention of the DirectionArgument, but I'll change it to your suggestions.

2023-06-05 22:23 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/features/commands/ColoredFeature.java
> +    public static final Argument<ColoredBlockArgument> blockType = Argument.ofType(material());
Yep

2023-06-06 13:29 UTC, Matthias1590 requested changes

2023-06-06 13:29 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/ColoredBlockTypeArgument.java
> +public enum ColoredBlockTypeArgument {
I dont think this should have Argument in its name since its just a colored block type, nothing more than that

2023-06-06 14:45 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/utils/ColoredBlockTypeArgument.java
> +public enum ColoredBlockTypeArgument {
I guess it's technically not specifically for the arguments, so I'll change it

2023-06-06 16:12 UTC, Matthias1590 commented
You didnt change anything? Are you sure you pushed your changes?

2023-06-06 16:12 UTC, maghedo243 commented
> You didnt change anything? Are you sure you pushed your changes?

Pretty sure yeah. I can see them here

2023-06-06 16:17 UTC, Matthias1590 commented
Wait what I think github wasnt showing them, my bad

2023-06-06 16:33 UTC, Matthias1590 commented
The same happens when looking at a non colored block such as oak stairs

2023-06-06 16:34 UTC, Matthias1590 commented
Doesnt seem to work when looking at any colored block either

2023-06-06 16:48 UTC, Matthias1590 commented
Yeah my bad this works perfectly fine

2023-06-06 16:49 UTC, merged