ss-command-feature
RedstoneTools/redstonetools-mod pull request #271
Opened 2023-06-08 14:15 UTC by JohanVonElectrum

Generalized from barrels to any common signal provider block and for all possible ss.

2023-06-08 14:21 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +public class SsCommandFeature extends CommandFeature {
could probably be named SignalStrengthBlockFeature

2023-06-08 14:21 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +    private final static SimpleCommandExceptionType INVALID_SIGNAL_STRENGTH = new SimpleCommandExceptionType(Text.of("Invalid signal strength!"));
This isnt used anywhere

2023-06-08 14:22 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +    public static final Argument<SignalBlock> block = Argument
I dont think theres a reason to let the user pick the type of block

2023-06-08 14:24 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +    protected Feedback execute(ServerCommandSource source) throws CommandSyntaxException {
This doesnt throw a CommandSyntaxException

2023-06-08 14:26 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +            source.getPlayer().giveItemStack(block.getValue().getItemStack(signalStrength.getValue()));
Could this be abstracted? Its rather unreadable like this

2023-06-08 14:27 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +    public static final Argument<SignalBlock> block = Argument
Just an if statement should be enough to decide whether to use a barrel or a command block

2023-06-08 14:28 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlock.java
> +public enum SignalBlock {
A bit overkill imo, especially since the type of block doesnt really matter

2023-06-08 14:28 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +public interface SignalBlockSupplier {
This also wouldnt be necessary with a simple if statement

2023-06-08 19:05 UTC, Matthias1590 commented
Theres still some unresolved convos

2023-06-08 19:55 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +@Feature(name = "Signal Strength Block", description = "Creates a block with the specified signal strength.", command = "ss")
Sure? It's replacement of previous /ss

2023-06-09 17:31 UTC, Matthias1590 requested changes

2023-06-09 17:31 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +    protected Feedback execute(ServerCommandSource source) throws CommandSyntaxException {
My bad

2023-06-09 17:31 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +            source.getPlayer().giveItemStack(block.getValue().getItemStack(signalStrength.getValue()));
Maybe put some parts into methods that have meaningful names cause rn its kinda hard to see what it actually does

2023-06-09 17:31 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlock.java
> +    SignalBlock(Block block, SignalBlockSupplier supplier) {
Do we need suppliers? Can't we just have some max capacity or something?

2023-06-09 17:31 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlock.java
> +    public static SignalBlock getBestBlock(int signal) {
Could you move this below the constructor?

2023-06-09 17:31 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlock.java
> +        else return COMMAND_BLOCK;
This could just be a ternary statement
```java
return signal <= 1779
    ? BARREL
    : COMMAND_BLOCK;
```

2023-06-09 17:31 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlock.java
> +        else return supplier.get(block, signal);
the else isnt needed here, could also be a ternary statement but since its quite some code it might be nice to just move the line with else return down 1 and remove the return

2023-06-09 17:31 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlock.java
> +        if (block == null || supplier == null) return getBestBlock(signal).getItemStack(signal);
please but the bodies of if statements on the line under the if statement

2023-06-10 07:29 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlock.java
> +    SignalBlock(Block block, SignalBlockSupplier supplier) {
SignalBlockSupplier is to keep all the code to generate the nbt together. Each possible NBT has a supplier: command_block, container, composter (And I have to add jukebox in 1.19). What we can do is to remove the `container_x()` suppliers and replace them with calls to `container(x)`.

2023-06-10 07:33 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/features/commands/SignalStrengthBlockFeature.java
>  @Feature(name = "Signal Strength Block", description = "Creates a block with the specified signal strength.", command = "ss")
It is fixed in the previous commit: https://github.com/RedstoneTools/redstonetools-mod/pull/271/commits/84bc123451b336c7be5a468b2544b2f699663b87

2023-06-10 07:41 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/features/commands/SsCommandFeature.java
> +            source.getPlayer().giveItemStack(block.getValue().getItemStack(signalStrength.getValue()));
I think the changes at https://github.com/RedstoneTools/redstonetools-mod/pull/271/commits/aed52ee1c0b2a0e46938e0bf527b71840a9bd42c are sufficient.

2023-06-10 07:44 UTC, JohanVonElectrum commented
I need some feedback on this one: https://github.com/RedstoneTools/redstonetools-mod/pull/271#discussion_r1225180354

2023-06-11 16:15 UTC, JayMensink commented
Mention the appropriate issue next time.
Issue #246

2023-06-11 16:23 UTC, JohanVonElectrum commented
Sorry, I talked about the issue on discord. I didn't know it was open on GitHub. For the next one I will check.

2023-06-11 16:42 UTC, Matthias1590 requested changes

2023-06-11 16:42 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    static SignalBlockSupplier container(int slots) {
doesnt adhere to srp, refactoring would probably make it more readable

2023-06-11 16:42 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    default ItemStack get(Block block, int signal) {
doesnt adhere to srp, which makes it a bit unreadable

2023-06-11 16:42 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +public interface SignalBlockSupplier {
why is this an interface with default implementations? i think just a class would be fine

2023-06-11 17:57 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +public interface SignalBlockSupplier {
I have chosen to use an interface with a build method (could be renamed to getNbt or buildNbt or something similar) and a default get method (could be renamed to getItemStack() or buildItemStack() or something similar) in order to provide a functional interface approach to generate NbtCompund based on an integer signal value, mimicking the Function<Integer, NbtCompound> interface. This allows flexibility and code reuse by allowing different implementations of the SignalBlockSupplier interface.

2023-06-11 17:57 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    default ItemStack get(Block block, int signal) {
I understand your concern about SRP and agree that separating responsibilities can improve readability. In the current implementation, the get method is responsible for both creating the ItemStack and applying the NbtCompund. The problem is that I can't think of a better place to put it and I think this is not a bad place at all.

2023-06-11 17:57 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    static SignalBlockSupplier container(int slots) {
I recognize the need for improved readability and maintainability. The container method and similar static methods serve as factory methods to generate instances of the SignalBlockSupplier interface with predefined behavior. I could move these methods to a class called SignalBlockSuppliers, but I'm not sure if it's worth it just for these 3 methods (although in 1.19 I have to add one more for the jukebox).

2023-06-11 18:55 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +public interface SignalBlockSupplier {
still think a class would do just fine

2023-06-11 18:58 UTC, Matthias1590 requested changes

2023-06-11 18:58 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    default ItemStack get(Block block, int signal) {
`if (signal < 0) throw new IllegalArgumentException("Signal cannot be negative");` could become `verifySignalStrength(signal)`, `signal` could be renamed to `signalStrength`, `get` should probably be called `getItemStack`, the portion of the code that creates the text could be extracted and put in another function, stuff like that

2023-06-11 18:58 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    static SignalBlockSupplier container(int slots) {
The location isnt the issue, its just the size of the method, theres constants everywhere that probably dont make a lot of sense to readers, `stack_size` uses snake case for some reason, theres 2 ternary operators in a single line, twice, the for loop is using 4 lines for the `for (...)` part, its just not very readable

2023-06-11 19:00 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    static SignalBlockSupplier container(int slots) {
I get your point on this, I'll see what I get to do with this.

2023-06-11 19:04 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    default ItemStack get(Block block, int signal) {
Okay, fair enough. The only problem is with the verifySignalStrength(signal) function. It's complicated because other illegal argument exceptions are thrown elsewhere due to other signal strength validations. Each signal block supplier has its own things to check, like a composter, which can't have signal 7, but can from 0-6 and 8.

2023-06-11 19:04 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +public interface SignalBlockSupplier {
I don't understand what you mean exactly.

2023-06-11 19:07 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    default ItemStack get(Block block, int signal) {
Then have it take a max ss

2023-06-11 19:07 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +public interface SignalBlockSupplier {
we can just use a class instead of an interface

2023-06-11 19:15 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +public interface SignalBlockSupplier {
keeping the interface as stated in discord

2023-06-11 19:16 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +    default ItemStack get(Block block, int signal) {
The problem with the composter can't be fixed like that, because max 8 included but can't 7. Composters can do [0, 6]U[8]

2023-06-12 20:12 UTC, DreiMu requested changes

2023-06-12 20:12 UTC, DreiMu commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +                throw new IllegalArgumentException("Container signal must be 0-1779");
There are some containers, e.g. furnaces, where this fails in lines 47-48, maybe add a calculation that changes the max value depending on the number of slots

2023-06-12 20:12 UTC, DreiMu commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +                throw new IllegalStateException("This signal strength cannot be achieved with the selected container");
It fails here

2023-06-12 20:57 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +                throw new IllegalArgumentException("Container signal must be 0-1779");
Intended. The isInvalidSignalStrength method checks the signal range, but containers with less than 15 slots have a discontinuous range, so some values do not work. This is not a bug, it is something impossible to fix, as stated in the comments on line 47.

2023-06-12 20:58 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +                throw new IllegalStateException("This signal strength cannot be achieved with the selected container");
It's not a bug, it's something on purpose. Read the comments on that line to understand why it happens.

2023-06-12 21:09 UTC, JohanVonElectrum commented on src/main/java/tools/redstone/redstonetools/utils/SignalBlockSupplier.java
> +                throw new IllegalArgumentException("Container signal must be 0-1779");
The catch in SignalStrengthBlockFeature for IllegalStateException was missing.

2023-06-12 21:47 UTC, DreiMu approved these changes
Until there is a better check/method for filling non-normal containers, this is probably the best solution

2023-06-14 17:35 UTC, merged