Issue #250 and then some
RedstoneTools/redstonetools-mod pull request #278
Opened 2023-06-09 22:20 UTC by maghedo243

This PR addresses Issue #250 and improves the /base output. It also adds a Number argument and associated classes for parsing a number in a command while keeping its originally entered base to be used later.

Besides this, there's a few tiny updates to the Update Mixin and the update screen

2023-06-10 00:15 UTC, xtrm-en commented
Tip: edit your PR to change to `fixes #250` so that Github automatically closes the issue when this PR gets merged :+1:

2023-06-10 20:53 UTC, maghedo243 commented
> Tip: edit your PR to change to `fixes #250` so that Github automatically closes the issue when this PR gets merged 👍

Edit the title? Or the first post?

2023-06-11 16:37 UTC, Matthias1590 requested changes

2023-06-11 16:37 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/NumberSerializer.java
> +public class NumberSerializer extends IntLikeSerializer<NumberArg> {
I think we should just make 1 serializer for all types of numbers when we refactor and just use the current ones for now

2023-06-11 16:37 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/mixin/update/CheckUpdateMixin.java
> +            //TODO REMEMBER TO REMOVE THE EXCLAMATION
?

2023-06-11 16:37 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/update/UpdateScreen.java
> +public class UpdateScreen extends ConfirmScreen {
Whats the purpose of this class

2023-06-11 16:37 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/utils/NumberArg.java
> +public class NumberArg implements Comparable<NumberArg>  {
Dont think we need this for now, we'll probably add something similar after 2.0.0

2023-06-11 16:39 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/IntLikeSerializer.java
> +                return isNegative ? tryParse("-"+number, numberBase.toInt()) : tryParse(number, numberBase.toInt());
It's a string at this point so you can't

2023-06-11 16:40 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/mixin/update/CheckUpdateMixin.java
> +            //TODO REMEMBER TO REMOVE THE EXCLAMATION
That's for me. It'll be gone when I'm done with the update screen

2023-06-11 16:40 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/update/UpdateScreen.java
> +public class UpdateScreen extends ConfirmScreen {
For the update screen when I start doing that. Remember I said I moved the screen creation outside of the UpdateMixin?

2023-06-11 16:41 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/utils/NumberArg.java
> +public class NumberArg implements Comparable<NumberArg>  {
Well I need this for the current base function or it literally won't work

2023-06-11 16:41 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/NumberSerializer.java
> +public class NumberSerializer extends IntLikeSerializer<NumberArg> {
That's fine, but I need this serializer for this feature so that I can store the base

2023-06-11 16:42 UTC, JayMensink commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/IntLikeSerializer.java
> +                return isNegative ? tryParse("-"+number, numberBase.toInt()) : tryParse(number, numberBase.toInt());
then cast it

2023-06-11 16:43 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/IntLikeSerializer.java
> +            serialized = serialized.replace("-","");
No, because it checks if there's a dash in the beginning. Technically if the user put two dashes it would work also, so maybe I'll add a condition for if there's more than one dash

2023-06-11 16:44 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/IntLikeSerializer.java
> +                return isNegative ? tryParse("-"+number, numberBase.toInt()) : tryParse(number, numberBase.toInt());
It parses it later. It's necessary to do it this way because of how the number parser works

2023-06-11 16:50 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/IntLikeSerializer.java
> +            serialized = serialized.replace("-","");
thats what i meant, probably couldve been more clear, mb

2023-06-11 16:51 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/IntLikeSerializer.java
> +                return isNegative ? tryParse("-"+number, numberBase.toInt()) : tryParse(number, numberBase.toInt());
tryParse returns a number, why cant you multiply that with -1

2023-06-11 16:51 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/NumberSerializer.java
> +public class NumberSerializer extends IntLikeSerializer<NumberArg> {
I think we should add storing the base later

2023-06-11 16:52 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/update/UpdateScreen.java
> +public class UpdateScreen extends ConfirmScreen {
right, i see, probably would make more sense to do that in that pr but this works ig

2023-06-11 16:54 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/IntLikeSerializer.java
> +                return isNegative ? tryParse("-"+number, numberBase.toInt()) : tryParse(number, numberBase.toInt());
I could do it there too

2023-06-11 20:14 UTC, Matthias1590 commented
just a reminder for myself, test and merge

2023-06-11 20:34 UTC, maghedo243 commented on src/main/java/tools/redstone/redstonetools/features/arguments/serializers/IntLikeSerializer.java
> +                return isNegative ? tryParse("-"+number, numberBase.toInt()) : tryParse(number, numberBase.toInt());
Just learned that I can't since tryParse returns T

2023-06-12 17:26 UTC, Matthias1590 approved these changes

2023-06-14 03:20 UTC, maghedo243 commented
> `/base -0` doesnt work

Fixed

2023-06-19 13:26 UTC, merged