Toggleable feature arguments & AirPlace outline
RedstoneTools/redstonetools-mod pull request #286
Opened 2023-06-12 09:18 UTC by orbyfied

Made `Argument<T>` thread safe and made the feedback methods return `Feedback` so the type is accessible.

Adds the ability to do `/toggleableFeature arg1 arg2` to configure it instead of having to overload the command with a command feature.

Adds `showOutline` option to `/airplace`, when enabled it will display an outline shaped of the block you will place at the location it would be placed. For items it shows a full block to visualize the position.

2023-06-12 09:24 UTC, orbyfied commented
[Preview (Video) https://drive.google.com/file/d/1-MXQpS671J_4BVjcZaMM3bF2svqIP9uO/view?usp=sharing](https://drive.google.com/file/d/1-MXQpS671J_4BVjcZaMM3bF2svqIP9uO/view?usp=sharing)

2023-06-14 07:28 UTC, orbyfied commented
Test Results (All Pass):
- Mixins
- Injector
- Feedback 
- Command Features 
- Toggleable Features 
- Toggleable Features: Options Saved/Loaded
- Toggleable Features: Options Set/Get with commands 
- AirPlace 
- AirPlace: Outline 
- AirPlace: Don't use with rockets while flying w/ elytra
- AirPlace: Works with offhand

2023-06-14 12:00 UTC, Matthias1590 requested changes

2023-06-14 12:02 UTC, orbyfied commented on src/main/java/tools/redstone/redstonetools/features/feedback/Feedback.java
> +    public static Feedback none() {
Ok, but then I have to make all the types public otherwise they can't be accessed.

2023-06-14 12:03 UTC, orbyfied commented on src/main/java/tools/redstone/redstonetools/features/toggleable/ToggleableFeature.java
> +    public void toggle(boolean status) {
I'll rename it

2023-06-14 12:03 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/feedback/Feedback.java
> +    public static Feedback none() {
wdym, it worked earlier?

2023-06-14 12:03 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/features/feedback/Feedback.java
> +    public static Feedback none() {
oh I see

2023-06-19 13:38 UTC, Matthias1590 approved these changes

2023-06-19 13:42 UTC, Matthias1590 approved these changes

2023-06-23 21:24 UTC, Matthias1590 commented
@orbyfied could you change that in this pr actually? just to make sure

2023-06-23 21:24 UTC, merged